version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vkconf
      POSTGRES_PASSWORD: vkconf_secret
      POSTGRES_DB: vkcloud_conf
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
