import type { LucideIcon } from 'lucide-react';
import {
  CalendarDays,
  Clock,
  Menu,
  Download,
  HelpCircle,
  History,
  ImagePlus,
  LayoutDashboard,
  LogOut,
  Megaphone,
  MessageSquare,
  Mic2,
  Pencil,
  Plus,
  Settings,
  Trash2,
  Trophy,
  User,
  Users,
  X,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';

export { iconTokens, type IconSize } from './tokens';

export const panelIcons = {
  overview: LayoutDashboard,
  users: Users,
  speakers: Mic2,
  schedule: CalendarDays,
  quiz: Trophy,
  questions: HelpCircle,
  feedback: MessageSquare,
  notifications: Megaphone,
  settings: Settings,
  logout: LogOut,
  download: Download,
  edit: Pencil,
  add: Plus,
  delete: Trash2,
  close: X,
  photo: ImagePlus,
  history: History,
  pending: Clock,
  menu: Menu,
  reorderUp: ChevronUp,
  reorderDown: ChevronDown,
  user: User,
} satisfies Record<string, LucideIcon>;
